--- #YAML:1.0
name:                bw-db
version:             1.1.0
abstract:            ~
license:             ~
author:              
    - Bill Weinman (http://bw.org/)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    BW::Base:                      0
    BW::Constants:                 0
    DBI:                           1.52
    Digest::MD5:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
