# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         bw-db
version:      1.0.4
version_from: lib/BW/DB.pm
installdirs:  site
requires:
    BW::Base:                      0
    BW::Constants:                 0
    DBD::mysql:                    0
    DBI:                           0
    Digest::MD5:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
